[package]
edition = "2021"
authors = ["trevp", "Guanhao Yin <sopium@mysterious.site>", "Martin Milata <martin@martinmilata.cz>"]
license = "Unlicense"
name = "trezor-noise-protocol"
readme = "README.md"
repository = "https://github.com/trezor/noise-rust"
version = "0.2.1"
description = "Noise Protocol Framework implementation, customized."
keywords = ["noise"]
categories = ["cryptography"]

[dependencies]
heapless = { version = "0.9.2", default-features = false, features = ["zeroize"] }

[features]
default = ["use_std"]
use_std = []
use_alloc = []
